# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Bakunas Sandbox 3(fac1ea11-e5a7-4e74-8d7e-965344c54f56)'
    subscriptionId: 'fac1ea11-e5a7-4e74-8d7e-965344c54f56'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: './IaCDemo2-Deploy.json'
    csmParametersFile: './IaCDemo2-Deploy.parameters.json'
    overrideParameters: '-networkResourceGoup_Name IaC-Demo2-01-ADO -computeResourceGroup_Name IaC-Demo2-02-ADO'
    deploymentMode: 'Incremental'

