name: PR-WhatIf
env:
  region: eastus2
  resourceGroup: IaC-Demo-2-01
  templateFile: ./VNet.bicep
  templateParametersFile: ./VNet.parameters.jsonc

on:
  pull_request:
    branches:
    - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDS}}
      
    - name: Preview Changes
      uses: Azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.SUB_SANDBOX_3 }}
        resourceGroupName: ${{env.resourceGroup}}
        region: ${{env.region}}
        template: ${{env.templateFile}}
        parameters: ${{env.templateParametersFile}}
        additionalArguments: "--what-if"
